language: node_js
node_js:
 - "10.16.0"

 stages:
 - name: test_FE

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - npm install

cache:
  directories:
    - node_modules

jobs:
  include:
  - stage: test_FE
    install: skip
    script: npm run test-github

