language: node_js
node_js:
 - "10.16.0"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run test-github
